baseURL: "https://chichead.netlify.app/"
title: Orange Mansion
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-YZCBLF5F53

minify:
  disableXML: true
  minifyOutput: true

# for Search Page
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Orange Mansion
  description: "Keeping a small record of what I've learned for Data Analysis. Sometimes I do other stuff."
  keywords: [Blog, Portfolio, PaperMod]
  author: Chichead
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  math: true

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon/om_favicon.ico"
    favicon16x16: "/favicon/om_favicon-16x16.png"
    favicon32x32: "/favicon/om_favicon-32x32.png"
    apple_touch_icon: "/favicon/om_apple-touch-icon.png"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Orange Mansion"
    icon: /favicon/om_apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "오렌지 맨숀"
    Content: 귤 향 가득한 오렌지 맨숀입니다. 데이터 분석을 하며 공부한 내용을 소소하게 기록합니다. 가끔 주인장의 딴짓거리도 기록합니다.

  socialIcons:
    - name: github
      url: "https://github.com/chichead"
    - name: instagram
      url: "https://www.instagram.com/ahnhyemin/"
    - name: linkedin
      url: "https://www.linkedin.com/in/anhyemin/"
    - name: Email
      url: "mailto:adios9709@gmail.com"


  analytics:
    google:
      SiteVerificationTag: "rFfSV0XOUcCLeUDzkSIw1RTh6R7mKCN8GDsvyimvR7Q"


  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/chichead/hugo_blog/blob/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

  giscus:
    repo : "chichead/hugo_blog"
    repoID : "R_kgDOJuBhZQ"
    category : "Announcements"
    categoryID : "DIC_kwDOJuBhZc4CYYgQ"
    mapping : "og:title"
    dataStrict : "1"
    reactionsEnabled : "1"
    emitMetadata : "0"
    inputPosition : "bottom"
    theme : "preferred_color_scheme"
    lang : "ko"
    loading : "lazy"


menu:
  main:
    - identifier: Posts
      name: Posts
      url: /Posts/
      weight: 10
    - identifier: Categories
      name: Categories
      url: /Categories/
      weight: 20
    - identifier: Search
      name: Search
      url: /Search/
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true

markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    style: monokai
    tabWidth: 4
    
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai